// ui/src/components/wallets/wallet-selector.tsx
"use client";

import React from "react";
import { ChevronsUpDown } from "lucide-react";
import {
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
} from "@/components/ui/sidebar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

type Wallet = {
  id: string;
  name: string;
};

interface WalletSelectorProps {
  currentWallet: Wallet;
  wallets: Wallet[];
  onWalletChange: (wallet: Wallet) => void;
}

export function WalletSelector({
  currentWallet = { id: "1", name: "Wallet1" },
  wallets = [],
  onWalletChange = () => {},
}: Partial<WalletSelectorProps>) {
  // Use default wallets if none provided
  const allWallets = wallets.length > 0 
    ? wallets 
    : [
        { id: "1", name: "Wallet1" },
        { id: "2", name: "Wallet2" },
        { id: "3", name: "Wallet3" },
      ];

  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <SidebarMenuButton
              size="lg"
              className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
            >
              <div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
                {currentWallet.name.charAt(0)}
              </div>
              <div className="grid flex-1 text-left text-sm leading-tight">
                <span className="truncate font-semibold">
                  {currentWallet.name}
                </span>
              </div>
              <ChevronsUpDown className="ml-auto" />
            </SidebarMenuButton>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="start" className="w-[200px]">
            {allWallets.map((wallet) => (
              <DropdownMenuItem
                key={wallet.id}
                onClick={() => onWalletChange(wallet)}
              >
                {wallet.name}
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  );
}

// nuxt-ui/components/WalletSelector.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Wallet } from '~/types/wallet'
import { useSidebar } from "@/components/ui/sidebar";

interface Props {
  selectedWallet?: Wallet
  wallets?: Wallet[]
  onWalletChange?: (wallet: Wallet) => void
}

const props = withDefaults(defineProps<Props>(), {
  selectedWallet: undefined,
  wallets: () => [],
  onWalletChange: () => {}
})

// Get sidebar state
const sidebar = useSidebar()
const isMobile = computed(() => sidebar.isMobile.value)

// Computed properties for display
const displayChainType = computed(() => props.selectedWallet?.chainType || 'ethereum')
const displayName = computed(() => props.selectedWallet?.name || 'Select Wallet')

// Handle wallet selection
const handleWalletSelect = (wallet: Wallet) => {
  props.onWalletChange(wallet)
}
</script>

<template>
  <SidebarMenu>
    <SidebarMenuItem>
      <DropdownMenu>
        <DropdownMenuTrigger as-child>
          <div>
            <SidebarMenuButton
              size="lg"
              :class="{ 'bg-sidebar-accent text-sidebar-accent-foreground': $attrs['data-state'] === 'open' }"
            >
              <div class="flex aspect-square size-8 items-center justify-center rounded-md bg-sidebar-primary text-sidebar-primary-foreground">
                <Web3Icon :symbol="displayChainType" size="24" variant="mono" />
              </div>
              <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate font-semibold">
                  {{ displayName }}
                </span>
              </div>
              <Icon name="lucide:chevrons-up-down" class="ml-auto" />
            </SidebarMenuButton>
          </div>
        </DropdownMenuTrigger>
        <DropdownMenuContent
          class="w-[--radix-dropdown-menu-trigger-width] min-w-[200px]"
          :align="isMobile ? 'start' : 'start'"
          :side="isMobile ? 'bottom' : 'right'"
          :side-offset="4"
        >
          <template v-if="wallets && wallets.length > 0">
            <DropdownMenuItem
              v-for="wallet in wallets"
              :key="wallet.address"
              @click="handleWalletSelect(wallet)"
            >
              <div class="flex size-6 items-center justify-center rounded-md border bg-background">
                <Web3Icon :symbol="wallet.chainType" size="24" variant="mono" />
              </div>
              <span class="ml-2">{{ wallet.name }}</span>
            </DropdownMenuItem>
          </template>
          <div v-else class="p-3 text-sm text-muted-foreground">
            No wallets found
          </div>
        </DropdownMenuContent>
      </DropdownMenu>
    </SidebarMenuItem>
  </SidebarMenu>
</template>
